//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemesasJJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class cambio
    {
        public cambio()
        {
            this.remesas = new HashSet<remesas>();
        }
    
        public int id { get; set; }
        public Nullable<decimal> cambio1 { get; set; }
        public Nullable<decimal> bolivares { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> estatus { get; set; }
    
        public virtual ICollection<remesas> remesas { get; set; }
    }
}
