//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemesasJJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes
    {
        public clientes()
        {
            this.beneficiarios = new HashSet<beneficiarios>();
            this.remesas = new HashSet<remesas>();
        }
    
        public int id { get; set; }
        public string cedula { get; set; }
        public string nombreCompleto { get; set; }
        public string correo { get; set; }
        public string telefono { get; set; }
        public Nullable<System.DateTime> fechaIni { get; set; }
        public Nullable<System.DateTime> fechaLastP { get; set; }
        public string UltimaCuenta { get; set; }
        public Nullable<int> ultimoBeneficiario { get; set; }
    
        public virtual ICollection<beneficiarios> beneficiarios { get; set; }
        public virtual ICollection<remesas> remesas { get; set; }
    }
}
