//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemesasJJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class moneda
    {
        public moneda()
        {
            this.bancosempre = new HashSet<bancosempre>();
            this.bancostrans = new HashSet<bancostrans>();
            this.remesas = new HashSet<remesas>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string sing { get; set; }
    
        public virtual ICollection<bancosempre> bancosempre { get; set; }
        public virtual ICollection<bancostrans> bancostrans { get; set; }
        public virtual ICollection<remesas> remesas { get; set; }
    }
}
