//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemesasJJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagosremesa
    {
        public int id { get; set; }
        public int banco { get; set; }
        public string tickeID { get; set; }
        public int remesaType { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.DateTime> procesed { get; set; }
        public Nullable<int> estatus { get; set; }
        public Nullable<int> addedBy { get; set; }
        public Nullable<int> procesedBy { get; set; }
    
        public virtual pagotype pagotype { get; set; }
    }
}
