//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemesasJJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class roleacess
    {
        public int id { get; set; }
        public int roleid { get; set; }
        public int acesosid { get; set; }
    
        public virtual acesos acesos { get; set; }
        public virtual roles roles { get; set; }
    }
}
