//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemesasJJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class sendgrid
    {
        public int id { get; set; }
        public string llave { get; set; }
        public string usuarioSendGrid { get; set; }
        public string ClaveSendgrid { get; set; }
        public string usuarioEmail { get; set; }
        public string key { get; set; }
        public Nullable<int> correos { get; set; }
    }
}
