//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemesasJJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string correo { get; set; }
        public string clave { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string nombrex { get; set; }
        public string apellidos { get; set; }
        public string dni { get; set; }
        public Nullable<System.DateTime> fechanac { get; set; }
        public string telefonos { get; set; }
        public string genero { get; set; }
        public string direccionEntrega { get; set; }
        public Nullable<int> roleid { get; set; }
    
        public virtual roles roles { get; set; }
    }
}
